/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type { PromiseOrValue } from "../../../../common";
import type {
  MigratableMockV2,
  MigratableMockV2Interface,
} from "../../../../oz/mocks/SingleInheritanceInitializableMocks.sol/MigratableMockV2";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "value",
        type: "uint256",
      },
    ],
    name: "initialize",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "value",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "anotherValue",
        type: "uint256",
      },
    ],
    name: "migrate",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [],
    name: "x",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "y",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b506103b1806100206000396000f3fe60806040526004361061003f5760003560e01c80630c55699c146100445780633e54bacb1461006f578063a56dfe4a1461008b578063fe4b84df146100b6575b600080fd5b34801561005057600080fd5b506100596100d2565b604051610066919061021f565b60405180910390f35b6100896004803603810190610084919061026b565b6100d8565b005b34801561009757600080fd5b506100a061011f565b6040516100ad919061021f565b60405180910390f35b6100d060048036038101906100cb91906102ab565b610125565b005b60015481565b600260009054906101000a900460ff16156100f257600080fd5b81600181905550806003819055506001600260006101000a81548160ff0219169083151502179055505050565b60035481565b600060019054906101000a900460ff168061014b575060008054906101000a900460ff16155b61018a576040517f08c379a00000000000000000000000000000000000000000000000000000000081526004016101819061035b565b60405180910390fd5b60008060019054906101000a900460ff1615905080156101da576001600060016101000a81548160ff02191690831515021790555060016000806101000a81548160ff0219169083151502179055505b8160018190555080156102025760008060016101000a81548160ff0219169083151502179055505b5050565b6000819050919050565b61021981610206565b82525050565b60006020820190506102346000830184610210565b92915050565b600080fd5b61024881610206565b811461025357600080fd5b50565b6000813590506102658161023f565b92915050565b600080604083850312156102825761028161023a565b5b600061029085828601610256565b92505060206102a185828601610256565b9150509250929050565b6000602082840312156102c1576102c061023a565b5b60006102cf84828501610256565b91505092915050565b600082825260208201905092915050565b7f496e697469616c697a61626c653a20636f6e747261637420697320616c72656160008201527f647920696e697469616c697a6564000000000000000000000000000000000000602082015250565b6000610345602e836102d8565b9150610350826102e9565b604082019050919050565b6000602082019050818103600083015261037481610338565b905091905056fea2646970667358221220c0a279d26e58e56daede8af85ae8f76064c37c3ed5961123736c0a6b624a9ea864736f6c63430008090033";

type MigratableMockV2ConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: MigratableMockV2ConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class MigratableMockV2__factory extends ContractFactory {
  constructor(...args: MigratableMockV2ConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<MigratableMockV2> {
    return super.deploy(overrides || {}) as Promise<MigratableMockV2>;
  }
  override getDeployTransaction(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  override attach(address: string): MigratableMockV2 {
    return super.attach(address) as MigratableMockV2;
  }
  override connect(signer: Signer): MigratableMockV2__factory {
    return super.connect(signer) as MigratableMockV2__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): MigratableMockV2Interface {
    return new utils.Interface(_abi) as MigratableMockV2Interface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): MigratableMockV2 {
    return new Contract(address, _abi, signerOrProvider) as MigratableMockV2;
  }
}
