import r, { Action as rAction, ActionCreator as rActionCreator, ActionCreatorsMapObject as rActionCreatorsMapObject, ActionFromReducer as rActionFromReducer, ActionFromReducersMapObject as rActionFromReducersMapObject, AnyAction as rAnyAction, CombinedState as rCombinedState, DeepPartial as rDeepPartial, Dispatch as rDispatch, EmptyObject as rEmptyObject, Func0 as rFunc0, Func1 as rFunc1, Func2 as rFunc2, Func3 as rFunc3, Middleware as rMiddleware, MiddlewareAPI as rMiddlewareAPI, Observable as rObservable, Observer as rObserver, PreloadedState as rPreloadedState, Reducer as rReducer, ReducerFromReducersMapObject as rReducerFromReducersMapObject, ReducersMapObject as rReducersMapObject, StateFromReducersMapObject as rStateFromReducersMapObject, Store as rStore, StoreCreator as rStoreCreator, StoreEnhancer as rStoreEnhancer, StoreEnhancerStoreCreator as rStoreEnhancerStoreCreator, Unsubscribe as rUnsubscribe } from 'redux';
export declare type Action = rAction;
export declare type ActionCreator<A> = rActionCreator<A>;
export declare type ActionCreatorsMapObject = rActionCreatorsMapObject;
export declare type ActionFromReducer<R> = rActionFromReducer<R>;
export declare type ActionFromReducersMapObject<M> = rActionFromReducersMapObject<M>;
export declare type AnyAction = rAnyAction;
export declare type CombinedState<S> = rCombinedState<S>;
export declare type DeepPartial<T> = rDeepPartial<T>;
export declare type Dispatch = rDispatch;
export declare type EmptyObject = rEmptyObject;
export declare type Func0<R> = rFunc0<R>;
export declare type Func1<T1, R> = rFunc1<T1, R>;
export declare type Func2<T1, T2, R> = rFunc2<T1, T2, R>;
export declare type Func3<T1, T2, T3, R> = rFunc3<T1, T2, T3, R>;
export declare type Middleware = rMiddleware;
export declare type MiddlewareAPI = rMiddlewareAPI;
export declare type Observable<T> = rObservable<T>;
export declare type Observer<T> = rObserver<T>;
export declare type PreloadedState<S> = rPreloadedState<S>;
export declare type Reducer = rReducer;
export declare type ReducerFromReducersMapObject<M> = rReducerFromReducersMapObject<M>;
export declare type ReducersMapObject = rReducersMapObject;
export declare type StateFromReducersMapObject<M> = rStateFromReducersMapObject<M>;
export declare type Store = rStore;
export declare type StoreCreator = rStoreCreator;
export declare type StoreEnhancer = rStoreEnhancer;
export declare type StoreEnhancerStoreCreator = rStoreEnhancerStoreCreator;
export declare type Unsubscribe = rUnsubscribe;
export declare let applyMiddleware: typeof r.applyMiddleware;
export declare let bindActionCreators: typeof r.bindActionCreators;
export declare let combineReducers: typeof r.combineReducers;
export declare let compose: typeof r.compose;
export declare let createStore: typeof r.createStore;
export declare let legacy_createStore: typeof r.legacy_createStore;
