/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type { PromiseOrValue } from "../../../../common";
import type {
  Implementation4,
  Implementation4Interface,
} from "../../../../oz/mocks/RegressionImplementation.sol/Implementation4";

const _abi = [
  {
    stateMutability: "nonpayable",
    type: "fallback",
  },
  {
    inputs: [],
    name: "getValue",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "initialize",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_number",
        type: "uint256",
      },
    ],
    name: "setValue",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b506102eb806100206000396000f3fe608060405234801561001057600080fd5b50600436106100455760003560e01c8063209652551461004f578063552410771461006d5780638129fc1c1461008957610046565b5b60018081905550005b610057610093565b6040516100649190610199565b60405180910390f35b610087600480360381019061008291906101e5565b61009d565b005b6100916100a7565b005b6000600154905090565b8060018190555050565b600060019054906101000a900460ff16806100cd575060008054906101000a900460ff16155b61010c576040517f08c379a000000000000000000000000000000000000000000000000000000000815260040161010390610295565b60405180910390fd5b60008060019054906101000a900460ff16159050801561015c576001600060016101000a81548160ff02191690831515021790555060016000806101000a81548160ff0219169083151502179055505b801561017d5760008060016101000a81548160ff0219169083151502179055505b50565b6000819050919050565b61019381610180565b82525050565b60006020820190506101ae600083018461018a565b92915050565b600080fd5b6101c281610180565b81146101cd57600080fd5b50565b6000813590506101df816101b9565b92915050565b6000602082840312156101fb576101fa6101b4565b5b6000610209848285016101d0565b91505092915050565b600082825260208201905092915050565b7f496e697469616c697a61626c653a20636f6e747261637420697320616c72656160008201527f647920696e697469616c697a6564000000000000000000000000000000000000602082015250565b600061027f602e83610212565b915061028a82610223565b604082019050919050565b600060208201905081810360008301526102ae81610272565b905091905056fea264697066735822122019d77ac6910d263cd2e2df186e46ab0d76b3272ffeee35687fbd1f82afaa5da164736f6c63430008090033";

type Implementation4ConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: Implementation4ConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class Implementation4__factory extends ContractFactory {
  constructor(...args: Implementation4ConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<Implementation4> {
    return super.deploy(overrides || {}) as Promise<Implementation4>;
  }
  override getDeployTransaction(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  override attach(address: string): Implementation4 {
    return super.attach(address) as Implementation4;
  }
  override connect(signer: Signer): Implementation4__factory {
    return super.connect(signer) as Implementation4__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): Implementation4Interface {
    return new utils.Interface(_abi) as Implementation4Interface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): Implementation4 {
    return new Contract(address, _abi, signerOrProvider) as Implementation4;
  }
}
