/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type { PromiseOrValue } from "../../../../common";
import type {
  Implementation2,
  Implementation2Interface,
} from "../../../../oz/mocks/RegressionImplementation.sol/Implementation2";

const _abi = [
  {
    inputs: [],
    name: "getValue",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "initialize",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_number",
        type: "uint256",
      },
    ],
    name: "setValue",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b506102e2806100206000396000f3fe608060405234801561001057600080fd5b50600436106100415760003560e01c8063209652551461004657806355241077146100645780638129fc1c14610080575b600080fd5b61004e61008a565b60405161005b9190610190565b60405180910390f35b61007e600480360381019061007991906101dc565b610094565b005b61008861009e565b005b6000600154905090565b8060018190555050565b600060019054906101000a900460ff16806100c4575060008054906101000a900460ff16155b610103576040517f08c379a00000000000000000000000000000000000000000000000000000000081526004016100fa9061028c565b60405180910390fd5b60008060019054906101000a900460ff161590508015610153576001600060016101000a81548160ff02191690831515021790555060016000806101000a81548160ff0219169083151502179055505b80156101745760008060016101000a81548160ff0219169083151502179055505b50565b6000819050919050565b61018a81610177565b82525050565b60006020820190506101a56000830184610181565b92915050565b600080fd5b6101b981610177565b81146101c457600080fd5b50565b6000813590506101d6816101b0565b92915050565b6000602082840312156101f2576101f16101ab565b5b6000610200848285016101c7565b91505092915050565b600082825260208201905092915050565b7f496e697469616c697a61626c653a20636f6e747261637420697320616c72656160008201527f647920696e697469616c697a6564000000000000000000000000000000000000602082015250565b6000610276602e83610209565b91506102818261021a565b604082019050919050565b600060208201905081810360008301526102a581610269565b905091905056fea2646970667358221220549e379023a8552badd4455318554d48a6677e4f172d1ed95a39cdef85d3f1e464736f6c63430008090033";

type Implementation2ConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: Implementation2ConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class Implementation2__factory extends ContractFactory {
  constructor(...args: Implementation2ConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<Implementation2> {
    return super.deploy(overrides || {}) as Promise<Implementation2>;
  }
  override getDeployTransaction(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  override attach(address: string): Implementation2 {
    return super.attach(address) as Implementation2;
  }
  override connect(signer: Signer): Implementation2__factory {
    return super.connect(signer) as Implementation2__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): Implementation2Interface {
    return new utils.Interface(_abi) as Implementation2Interface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): Implementation2 {
    return new Contract(address, _abi, signerOrProvider) as Implementation2;
  }
}
