import * as tlUserEvent from '@testing-library/user-event';
export declare type PointerEventsCheckLevel = tlUserEvent.PointerEventsCheckLevel;
export declare let EachApiCall: tlUserEvent.PointerEventsCheckLevel;
export declare let EachTarget: tlUserEvent.PointerEventsCheckLevel;
export declare let EachTrigger: tlUserEvent.PointerEventsCheckLevel;
export declare let Never: tlUserEvent.PointerEventsCheckLevel;
export declare let clear: typeof import("@testing-library/user-event/dist/types/setup/directApi").clear;
export declare let click: typeof import("@testing-library/user-event/dist/types/setup/directApi").click;
export declare let copy: typeof import("@testing-library/user-event/dist/types/setup/directApi").copy;
export declare let cut: typeof import("@testing-library/user-event/dist/types/setup/directApi").cut;
export declare let dblClick: typeof import("@testing-library/user-event/dist/types/setup/directApi").dblClick;
export declare let deselectOptions: typeof import("@testing-library/user-event/dist/types/setup/directApi").deselectOptions;
export declare let hover: typeof import("@testing-library/user-event/dist/types/setup/directApi").hover;
export declare let keyboard: typeof import("@testing-library/user-event/dist/types/setup/directApi").keyboard;
export declare let paste: typeof import("@testing-library/user-event/dist/types/setup/directApi").paste;
export declare let pointer: typeof import("@testing-library/user-event/dist/types/setup/directApi").pointer;
export declare let selectOptions: typeof import("@testing-library/user-event/dist/types/setup/directApi").selectOptions;
export declare let setup: typeof import("@testing-library/user-event/dist/types/setup/setup").setupMain;
export declare let tab: typeof import("@testing-library/user-event/dist/types/setup/directApi").tab;
export declare let tripleClick: typeof import("@testing-library/user-event/dist/types/setup/directApi").tripleClick;
export declare let type: typeof import("@testing-library/user-event/dist/types/setup/directApi").type;
export declare let unhover: typeof import("@testing-library/user-event/dist/types/setup/directApi").unhover;
export declare let upload: typeof import("@testing-library/user-event/dist/types/setup/directApi").upload;
