import c, { Canvas as cCanvas, CanvasGradient as cCanvasGradient, CanvasPattern as cCanvasPattern, CanvasRenderingContext2D as cCanvasRenderingContext2D, DOMMatrix as cDOMMatrix, DOMPoint as cDOMPoint, JPEGStream as cJPEGStream, JpegConfig as cJpegConfig, Image as cImage, ImageData as cImageData, NodeCanvasRenderingContext2DSettings as cNodeCanvasRenderingContext2DSettings, PDFStream as cPDFStream, PNGStream as cPNGStream, PdfConfig as cPdfConfig, PngConfig as cPngConfig } from 'canvas';
export declare type Canvas = cCanvas;
export declare type CanvasGradient = cCanvasGradient;
export declare type CanvasPattern = cCanvasPattern;
export declare type CanvasRenderingContext2D = cCanvasRenderingContext2D;
export declare type DOMMatrix = cDOMMatrix;
export declare type DOMPoint = cDOMPoint;
export declare type JPEGStream = cJPEGStream;
export declare type JpegConfig = cJpegConfig;
export declare type Image = cImage;
export declare type ImageData = cImageData;
export declare type NodeCanvasRenderingContext2DSettings = cNodeCanvasRenderingContext2DSettings;
export declare type PDFStream = cPDFStream;
export declare type PNGStream = cPNGStream;
export declare type PdfConfig = cPdfConfig;
export declare type PngConfig = cPngConfig;
declare let exportObj: {
    freetypeVersion: string;
    gifVersion: string;
    jpegVersion: string;
    loadImage: typeof c.loadImage;
    registerFont: typeof c.registerFont;
    rsvgVersion: string;
    version: string;
    cairoVersion: string;
    createCanvas: typeof c.createCanvas;
    createImageData: typeof c.createImageData;
};
export default exportObj;
