/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../common";

export interface InitializableMockInterface extends utils.Interface {
  functions: {
    "fail()": FunctionFragment;
    "initialize()": FunctionFragment;
    "initializeNested()": FunctionFragment;
    "initializeWithX(uint256)": FunctionFragment;
    "initializerRan()": FunctionFragment;
    "nonInitializable(uint256)": FunctionFragment;
    "x()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "fail"
      | "initialize"
      | "initializeNested"
      | "initializeWithX"
      | "initializerRan"
      | "nonInitializable"
      | "x"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "fail", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "initializeNested",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "initializeWithX",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "initializerRan",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "nonInitializable",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(functionFragment: "x", values?: undefined): string;

  decodeFunctionResult(functionFragment: "fail", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "initializeNested",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "initializeWithX",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "initializerRan",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nonInitializable",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "x", data: BytesLike): Result;

  events: {};
}

export interface InitializableMock extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: InitializableMockInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    fail(overrides?: CallOverrides): Promise<[void]>;

    initialize(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    initializeNested(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    initializeWithX(
      _x: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    initializerRan(overrides?: CallOverrides): Promise<[boolean]>;

    nonInitializable(
      _x: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    x(overrides?: CallOverrides): Promise<[BigNumber]>;
  };

  fail(overrides?: CallOverrides): Promise<void>;

  initialize(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  initializeNested(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  initializeWithX(
    _x: PromiseOrValue<BigNumberish>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  initializerRan(overrides?: CallOverrides): Promise<boolean>;

  nonInitializable(
    _x: PromiseOrValue<BigNumberish>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  x(overrides?: CallOverrides): Promise<BigNumber>;

  callStatic: {
    fail(overrides?: CallOverrides): Promise<void>;

    initialize(overrides?: CallOverrides): Promise<void>;

    initializeNested(overrides?: CallOverrides): Promise<void>;

    initializeWithX(
      _x: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    initializerRan(overrides?: CallOverrides): Promise<boolean>;

    nonInitializable(
      _x: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    x(overrides?: CallOverrides): Promise<BigNumber>;
  };

  filters: {};

  estimateGas: {
    fail(overrides?: CallOverrides): Promise<BigNumber>;

    initialize(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    initializeNested(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    initializeWithX(
      _x: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    initializerRan(overrides?: CallOverrides): Promise<BigNumber>;

    nonInitializable(
      _x: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    x(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    fail(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    initialize(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    initializeNested(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    initializeWithX(
      _x: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    initializerRan(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    nonInitializable(
      _x: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    x(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
