/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../common";

export interface MerkleProofWrapperInterface extends utils.Interface {
  functions: {
    "processProof(bytes32[],bytes32)": FunctionFragment;
    "verify(bytes32[],bytes32,bytes32)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: "processProof" | "verify"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "processProof",
    values: [PromiseOrValue<BytesLike>[], PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "verify",
    values: [
      PromiseOrValue<BytesLike>[],
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "processProof",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "verify", data: BytesLike): Result;

  events: {};
}

export interface MerkleProofWrapper extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: MerkleProofWrapperInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    processProof(
      proof: PromiseOrValue<BytesLike>[],
      leaf: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    verify(
      proof: PromiseOrValue<BytesLike>[],
      root: PromiseOrValue<BytesLike>,
      leaf: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;
  };

  processProof(
    proof: PromiseOrValue<BytesLike>[],
    leaf: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<string>;

  verify(
    proof: PromiseOrValue<BytesLike>[],
    root: PromiseOrValue<BytesLike>,
    leaf: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  callStatic: {
    processProof(
      proof: PromiseOrValue<BytesLike>[],
      leaf: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<string>;

    verify(
      proof: PromiseOrValue<BytesLike>[],
      root: PromiseOrValue<BytesLike>,
      leaf: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<boolean>;
  };

  filters: {};

  estimateGas: {
    processProof(
      proof: PromiseOrValue<BytesLike>[],
      leaf: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    verify(
      proof: PromiseOrValue<BytesLike>[],
      root: PromiseOrValue<BytesLike>,
      leaf: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    processProof(
      proof: PromiseOrValue<BytesLike>[],
      leaf: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    verify(
      proof: PromiseOrValue<BytesLike>[],
      root: PromiseOrValue<BytesLike>,
      leaf: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
