/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../common";

export interface SafeMathMockInterface extends utils.Interface {
  functions: {
    "addMemoryCheck()": FunctionFragment;
    "divMemoryCheck()": FunctionFragment;
    "divWithMessage(uint256,uint256,string)": FunctionFragment;
    "doAdd(uint256,uint256)": FunctionFragment;
    "doDiv(uint256,uint256)": FunctionFragment;
    "doMod(uint256,uint256)": FunctionFragment;
    "doMul(uint256,uint256)": FunctionFragment;
    "doSub(uint256,uint256)": FunctionFragment;
    "modMemoryCheck()": FunctionFragment;
    "modWithMessage(uint256,uint256,string)": FunctionFragment;
    "mulMemoryCheck()": FunctionFragment;
    "subMemoryCheck()": FunctionFragment;
    "subWithMessage(uint256,uint256,string)": FunctionFragment;
    "tryAdd(uint256,uint256)": FunctionFragment;
    "tryDiv(uint256,uint256)": FunctionFragment;
    "tryMod(uint256,uint256)": FunctionFragment;
    "tryMul(uint256,uint256)": FunctionFragment;
    "trySub(uint256,uint256)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "addMemoryCheck"
      | "divMemoryCheck"
      | "divWithMessage"
      | "doAdd"
      | "doDiv"
      | "doMod"
      | "doMul"
      | "doSub"
      | "modMemoryCheck"
      | "modWithMessage"
      | "mulMemoryCheck"
      | "subMemoryCheck"
      | "subWithMessage"
      | "tryAdd"
      | "tryDiv"
      | "tryMod"
      | "tryMul"
      | "trySub"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "addMemoryCheck",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "divMemoryCheck",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "divWithMessage",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "doAdd",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "doDiv",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "doMod",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "doMul",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "doSub",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "modMemoryCheck",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "modWithMessage",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "mulMemoryCheck",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "subMemoryCheck",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "subWithMessage",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "tryAdd",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "tryDiv",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "tryMod",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "tryMul",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "trySub",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
  ): string;

  decodeFunctionResult(
    functionFragment: "addMemoryCheck",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "divMemoryCheck",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "divWithMessage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "doAdd", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "doDiv", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "doMod", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "doMul", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "doSub", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "modMemoryCheck",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "modWithMessage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "mulMemoryCheck",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "subMemoryCheck",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "subWithMessage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "tryAdd", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "tryDiv", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "tryMod", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "tryMul", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "trySub", data: BytesLike): Result;

  events: {};
}

export interface SafeMathMock extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: SafeMathMockInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    addMemoryCheck(
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { mem: BigNumber }>;

    divMemoryCheck(
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { mem: BigNumber }>;

    divWithMessage(
      a: PromiseOrValue<BigNumberish>,
      b: PromiseOrValue<BigNumberish>,
      errorMessage: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    doAdd(
      a: PromiseOrValue<BigNumberish>,
      b: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    doDiv(
      a: PromiseOrValue<BigNumberish>,
      b: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    doMod(
      a: PromiseOrValue<BigNumberish>,
      b: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    doMul(
      a: PromiseOrValue<BigNumberish>,
      b: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    doSub(
      a: PromiseOrValue<BigNumberish>,
      b: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    modMemoryCheck(
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { mem: BigNumber }>;

    modWithMessage(
      a: PromiseOrValue<BigNumberish>,
      b: PromiseOrValue<BigNumberish>,
      errorMessage: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    mulMemoryCheck(
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { mem: BigNumber }>;

    subMemoryCheck(
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { mem: BigNumber }>;

    subWithMessage(
      a: PromiseOrValue<BigNumberish>,
      b: PromiseOrValue<BigNumberish>,
      errorMessage: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    tryAdd(
      a: PromiseOrValue<BigNumberish>,
      b: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[boolean, BigNumber] & { flag: boolean; value: BigNumber }>;

    tryDiv(
      a: PromiseOrValue<BigNumberish>,
      b: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[boolean, BigNumber] & { flag: boolean; value: BigNumber }>;

    tryMod(
      a: PromiseOrValue<BigNumberish>,
      b: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[boolean, BigNumber] & { flag: boolean; value: BigNumber }>;

    tryMul(
      a: PromiseOrValue<BigNumberish>,
      b: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[boolean, BigNumber] & { flag: boolean; value: BigNumber }>;

    trySub(
      a: PromiseOrValue<BigNumberish>,
      b: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[boolean, BigNumber] & { flag: boolean; value: BigNumber }>;
  };

  addMemoryCheck(overrides?: CallOverrides): Promise<BigNumber>;

  divMemoryCheck(overrides?: CallOverrides): Promise<BigNumber>;

  divWithMessage(
    a: PromiseOrValue<BigNumberish>,
    b: PromiseOrValue<BigNumberish>,
    errorMessage: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  doAdd(
    a: PromiseOrValue<BigNumberish>,
    b: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  doDiv(
    a: PromiseOrValue<BigNumberish>,
    b: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  doMod(
    a: PromiseOrValue<BigNumberish>,
    b: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  doMul(
    a: PromiseOrValue<BigNumberish>,
    b: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  doSub(
    a: PromiseOrValue<BigNumberish>,
    b: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  modMemoryCheck(overrides?: CallOverrides): Promise<BigNumber>;

  modWithMessage(
    a: PromiseOrValue<BigNumberish>,
    b: PromiseOrValue<BigNumberish>,
    errorMessage: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  mulMemoryCheck(overrides?: CallOverrides): Promise<BigNumber>;

  subMemoryCheck(overrides?: CallOverrides): Promise<BigNumber>;

  subWithMessage(
    a: PromiseOrValue<BigNumberish>,
    b: PromiseOrValue<BigNumberish>,
    errorMessage: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  tryAdd(
    a: PromiseOrValue<BigNumberish>,
    b: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<[boolean, BigNumber] & { flag: boolean; value: BigNumber }>;

  tryDiv(
    a: PromiseOrValue<BigNumberish>,
    b: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<[boolean, BigNumber] & { flag: boolean; value: BigNumber }>;

  tryMod(
    a: PromiseOrValue<BigNumberish>,
    b: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<[boolean, BigNumber] & { flag: boolean; value: BigNumber }>;

  tryMul(
    a: PromiseOrValue<BigNumberish>,
    b: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<[boolean, BigNumber] & { flag: boolean; value: BigNumber }>;

  trySub(
    a: PromiseOrValue<BigNumberish>,
    b: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<[boolean, BigNumber] & { flag: boolean; value: BigNumber }>;

  callStatic: {
    addMemoryCheck(overrides?: CallOverrides): Promise<BigNumber>;

    divMemoryCheck(overrides?: CallOverrides): Promise<BigNumber>;

    divWithMessage(
      a: PromiseOrValue<BigNumberish>,
      b: PromiseOrValue<BigNumberish>,
      errorMessage: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    doAdd(
      a: PromiseOrValue<BigNumberish>,
      b: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    doDiv(
      a: PromiseOrValue<BigNumberish>,
      b: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    doMod(
      a: PromiseOrValue<BigNumberish>,
      b: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    doMul(
      a: PromiseOrValue<BigNumberish>,
      b: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    doSub(
      a: PromiseOrValue<BigNumberish>,
      b: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    modMemoryCheck(overrides?: CallOverrides): Promise<BigNumber>;

    modWithMessage(
      a: PromiseOrValue<BigNumberish>,
      b: PromiseOrValue<BigNumberish>,
      errorMessage: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    mulMemoryCheck(overrides?: CallOverrides): Promise<BigNumber>;

    subMemoryCheck(overrides?: CallOverrides): Promise<BigNumber>;

    subWithMessage(
      a: PromiseOrValue<BigNumberish>,
      b: PromiseOrValue<BigNumberish>,
      errorMessage: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    tryAdd(
      a: PromiseOrValue<BigNumberish>,
      b: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[boolean, BigNumber] & { flag: boolean; value: BigNumber }>;

    tryDiv(
      a: PromiseOrValue<BigNumberish>,
      b: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[boolean, BigNumber] & { flag: boolean; value: BigNumber }>;

    tryMod(
      a: PromiseOrValue<BigNumberish>,
      b: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[boolean, BigNumber] & { flag: boolean; value: BigNumber }>;

    tryMul(
      a: PromiseOrValue<BigNumberish>,
      b: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[boolean, BigNumber] & { flag: boolean; value: BigNumber }>;

    trySub(
      a: PromiseOrValue<BigNumberish>,
      b: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[boolean, BigNumber] & { flag: boolean; value: BigNumber }>;
  };

  filters: {};

  estimateGas: {
    addMemoryCheck(overrides?: CallOverrides): Promise<BigNumber>;

    divMemoryCheck(overrides?: CallOverrides): Promise<BigNumber>;

    divWithMessage(
      a: PromiseOrValue<BigNumberish>,
      b: PromiseOrValue<BigNumberish>,
      errorMessage: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    doAdd(
      a: PromiseOrValue<BigNumberish>,
      b: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    doDiv(
      a: PromiseOrValue<BigNumberish>,
      b: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    doMod(
      a: PromiseOrValue<BigNumberish>,
      b: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    doMul(
      a: PromiseOrValue<BigNumberish>,
      b: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    doSub(
      a: PromiseOrValue<BigNumberish>,
      b: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    modMemoryCheck(overrides?: CallOverrides): Promise<BigNumber>;

    modWithMessage(
      a: PromiseOrValue<BigNumberish>,
      b: PromiseOrValue<BigNumberish>,
      errorMessage: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    mulMemoryCheck(overrides?: CallOverrides): Promise<BigNumber>;

    subMemoryCheck(overrides?: CallOverrides): Promise<BigNumber>;

    subWithMessage(
      a: PromiseOrValue<BigNumberish>,
      b: PromiseOrValue<BigNumberish>,
      errorMessage: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    tryAdd(
      a: PromiseOrValue<BigNumberish>,
      b: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    tryDiv(
      a: PromiseOrValue<BigNumberish>,
      b: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    tryMod(
      a: PromiseOrValue<BigNumberish>,
      b: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    tryMul(
      a: PromiseOrValue<BigNumberish>,
      b: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    trySub(
      a: PromiseOrValue<BigNumberish>,
      b: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    addMemoryCheck(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    divMemoryCheck(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    divWithMessage(
      a: PromiseOrValue<BigNumberish>,
      b: PromiseOrValue<BigNumberish>,
      errorMessage: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    doAdd(
      a: PromiseOrValue<BigNumberish>,
      b: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    doDiv(
      a: PromiseOrValue<BigNumberish>,
      b: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    doMod(
      a: PromiseOrValue<BigNumberish>,
      b: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    doMul(
      a: PromiseOrValue<BigNumberish>,
      b: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    doSub(
      a: PromiseOrValue<BigNumberish>,
      b: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    modMemoryCheck(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    modWithMessage(
      a: PromiseOrValue<BigNumberish>,
      b: PromiseOrValue<BigNumberish>,
      errorMessage: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    mulMemoryCheck(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    subMemoryCheck(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    subWithMessage(
      a: PromiseOrValue<BigNumberish>,
      b: PromiseOrValue<BigNumberish>,
      errorMessage: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    tryAdd(
      a: PromiseOrValue<BigNumberish>,
      b: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    tryDiv(
      a: PromiseOrValue<BigNumberish>,
      b: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    tryMod(
      a: PromiseOrValue<BigNumberish>,
      b: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    tryMul(
      a: PromiseOrValue<BigNumberish>,
      b: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    trySub(
      a: PromiseOrValue<BigNumberish>,
      b: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
