import * as SystemExport from "./src/System.js";
import * as PathExport from "./src/Path.js";
export * from "./src/Reader.js";
export * from "./lib/types/index.js";
declare let System: typeof SystemExport.System;
export default System;
export declare let TreeNode: typeof import("./src/TreeNode.js").TreeNode;
export declare type Dirent = SystemExport.Dirent;
export declare type ITreeNode = SystemExport.ITreeNodeExport;
export declare type ITree = SystemExport.ITreeExport;
export declare type IFile = SystemExport.IFileExport;
export declare type IFolder = SystemExport.IFolderExport;
export declare type IRoot = SystemExport.IRootExport;
export declare let system: SystemExport.System;
export declare let ZionPath: typeof PathExport.ZionPath;
