export * from "./src/GitHub.js";
export * from "./src/Git.js";
export * from "./src/Repo.js";
export * as dotenv from "dotenv";
export * from "./src/Types/index.js";
import * as GitHub from "./src/GitHub.js";
import * as Git from "./src/Git.js";
import * as Repo from "./src/Repo.js";
import * as dotenv from "dotenv";
declare const _default: {
    parse<T extends dotenv.DotenvParseOutput = dotenv.DotenvParseOutput>(src: string | Buffer): T;
    config(options?: dotenv.DotenvConfigOptions | undefined): dotenv.DotenvConfigOutput;
    Status: typeof Repo.Status;
    Repo: typeof Repo.Repo;
    testRepo(path: string | string[]): import("simple-git").Response<boolean>;
    initRepo(path: string | string[], options?: import("simple-git").TaskOptions<import("simple-git").Options> | undefined): import("simple-git").Response<import("simple-git").InitResult>;
    repoStatus(path: string | string[], options?: import("simple-git").TaskOptions<import("simple-git").Options> | undefined): Promise<import("simple-git").StatusResult>;
    repoHasRemote(path: string | string[]): Promise<boolean>;
    ZionGit: typeof Git.ZionGit;
    ZionGitHub: typeof GitHub.ZionGitHub;
};
export default _default;
