/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as copySol from "./copy.sol";
export type { copySol };
import type * as draftErc1155PermitSol from "./draft-ERC1155Permit.sol";
export type { draftErc1155PermitSol };
import type * as draftIerc1155PermitSol from "./draft-IERC1155Permit.sol";
export type { draftIerc1155PermitSol };
export type { ERC1155Master } from "./ERC1155Master";
export type { ERC1155Snapshot } from "./ERC1155Snapshot";
export type { ERC1155Supply } from "./ERC1155Supply";
export type { ERC1155Votes } from "./ERC1155Votes";
export type { ERC1155Wrapper } from "./ERC1155Wrapper";
export type { IERC1155Master } from "./IERC1155Master";
export type { IERC1155MetadataURI } from "./IERC1155MetadataURI";
export type { IERC1155Snapshot } from "./IERC1155Snapshot";
