import { MixinAny } from "../zionTypes.js";
declare type MixinDecoratorTypeAny = (mixin: any) => any;
declare type MixinDecoratorTypeMixinAny = (mixin: MixinAny) => {};
export declare const isApplicationOf: (proto: any, mixin: any) => any;
export declare const hasMixin: (o: any, mixin: any) => boolean;
declare type wrapType = (mixin: any, wrapper: any) => any;
export declare const wrap: wrapType;
declare type unwraptype = (wrapper: any) => any;
export declare const unwrap: unwraptype;
export declare const BaseMixin: MixinDecoratorTypeMixinAny;
export declare const Cached: MixinDecoratorTypeAny;
export declare const DeDupe: MixinDecoratorTypeAny;
export {};
