// DOFACTORY.mostraDesignPatternSenzaEsempi("Behavioral");
// DOFACTORY.mostraDesignPatternSenzaEsempi("Creational");
// DOFACTORY.mostraDesignPatternSenzaEsempi("Structural");
// DOFACTORY.contaDesignPatternSenzaEsempi();
// DOFACTORY.contaDesignPatternSenzaEsempi("Behavioral");
// DOFACTORY.contaDesignPatternSenzaEsempi("Creational");
// DOFACTORY.contaDesignPatternSenzaEsempi("Structural");
// factory.mostraSorgenti();
// PJDP.mostraPatternID(decorator);
// console.log(decTut1.file.path);
// console.log(Object.assign({}, nextRemarkRehype));
// Tutorial.mostraTutorials();
