import def from 'react-dom';
export let createPortal = def.createPortal;
export let findDOMNode = def.findDOMNode;
export let flushSync = def.flushSync;
export let hydrate = def.hydrate;
export let render = def.render;
export let unmountComponentAtNode = def.unmountComponentAtNode;
export let unstable_batchedUpdates = def.unstable_batchedUpdates;
export let unstable_renderSubtreeIntoContainer = def.unstable_renderSubtreeIntoContainer;
export let version = def.version;
