import def from 'react-dom';
export declare let createPortal: typeof def.createPortal;
export declare let findDOMNode: typeof def.findDOMNode;
export declare let flushSync: typeof def.flushSync;
export declare let hydrate: def.Renderer;
export declare let render: def.Renderer;
export declare let unmountComponentAtNode: typeof def.unmountComponentAtNode;
export declare let unstable_batchedUpdates: typeof def.unstable_batchedUpdates;
export declare let unstable_renderSubtreeIntoContainer: typeof def.unstable_renderSubtreeIntoContainer;
export declare let version: string;
