export declare let name: string;
export declare let protype: import("ipfs-http-client").CID;
export declare let isCID: typeof import("ipfs-http-client").CID.isCID;
export declare let asCID: typeof import("ipfs-http-client").CID.asCID;
export declare let create: typeof import("ipfs-http-client").CID.create;
export declare let createV0: typeof import("ipfs-http-client").CID.createV0;
export declare let createV1: typeof import("ipfs-http-client").CID.createV1;
export declare let decode: typeof import("ipfs-http-client").CID.decode;
export declare let decodeFirst: typeof import("ipfs-http-client").CID.decodeFirst;
export declare let instectBytes: typeof import("ipfs-http-client").CID.inspectBytes;
export declare let parse: typeof import("ipfs-http-client").CID.parse;
