/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as extentions from "./extentions";
export type { extentions };
export type { IZNFT } from "./IZNFT";
export type { ZNFT } from "./ZNFT";
