import * as IPFSHTTP from 'ipfs-http-client';
export declare type BlockCodec = IPFSHTTP.BlockCodec;
export declare type CID = IPFSHTTP.CID;
export declare type EndpointConfig = IPFSHTTP.EndpointConfig;
export declare type IPFSHTTPClient = IPFSHTTP.IPFSHTTPClient;
export declare type MultibaseCodec = IPFSHTTP.MultibaseCodec;
export declare type MultihashHasher = IPFSHTTP.MultihashHasher;
export declare type Options_T = IPFSHTTP.Options;
export declare type multiaddr = IPFSHTTP.multiaddr;
export declare let CID: typeof IPFSHTTP.CID;
export declare let create: typeof IPFSHTTP.create;
export declare let globSource: typeof import("ipfs-utils/src/files/glob-source");
export declare let multiaddr: typeof IPFSHTTP.multiaddr;
export declare let urlSource: typeof IPFSHTTP.urlSource;
export declare let module: any;
