import { IApp } from "../src/App.js";
declare type reportNumber = string;
export declare type BelieveRecord = {
    ["Mese di Reporting"]: Date;
    ["Mese di vendita"]: Date;
    Piattaforma: string;
    ["Paese / Regione"]: string;
    ["Nome dell'etichetta"]: string;
    ["Nome dell'artista"]: string;
    ["Titolo dell'uscita"]: string;
    ["Titolo della traccia"]: string;
    UPC: reportNumber;
    ISRC: reportNumber;
    ["Riferimento catalogo uscita"]: string;
    ["Tipo di sottoscrizione in streaming"]: string;
    ["Tipo di uscita"]: string;
    ["Tipo di vendita"]: string;
    Quantita: reportNumber;
    ["Valuta di pagamento del cliente"]: "EUR";
    ["Prezzo unitario"]: reportNumber;
    ["Tariffa di riproduzione meccanica"]: reportNumber;
    ["Profitto lordo"]: reportNumber;
    ["Tasso di profitto del cliente"]: reportNumber;
    ["Guadagno netto"]: reportNumber;
};
export declare function creaZionCsv(this: IApp, id: number): IApp;
export {};
