/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as erc1155StakingSol from "./ERC1155Staking.sol";
export type { erc1155StakingSol };
import type * as synthetixStakingSol from "./SynthetixStaking.sol";
export type { synthetixStakingSol };
export type { ERC1155VestingWallet } from "./ERC1155VestingWallet";
export type { ERC721Staking } from "./ERC721Staking";
export type { IERC1155Staking } from "./IERC1155Staking";
export type { IERC1155VestingWallet } from "./IERC1155VestingWallet";
export type { IERC721Staking } from "./IERC721Staking";
export type { IZionVestingWallet } from "./IZionVestingWallet";
export type { ZionVestingWallet } from "./ZionVestingWallet";
