import { AbstractElement as fscAbstractElement, Attributes as fscAttributes, DOM as fscDOM, FaSymbol as fscFaSymbol, FlipProp as fscFlipProp, FontawesomeObject as fscFontawesomeObject, Icon as fscIcon, IconDefinition as fscIconDefinition, IconLookup as fscIconLookup, IconName as fscIconName, IconPack as fscIconPack, IconParams as fscIconParams, IconPathData as fscIconPathData, IconPrefix as fscIconPrefix, IconProp as fscIconProp, Layer as fscLayer, LayerParams as fscLayerParams, Library as fscLibrary, Params as fscParams, PullProp as fscPullProp, RotateProp as fscRotateProp, SizeProp as fscSizeProp, Styles as fscStyles, Text as fscText, TextParams as fscTextParams, Transform as fscTransform } from '@fortawesome/fontawesome-svg-core';
import * as fsc from '@fortawesome/fontawesome-svg-core';
export declare type AbstractElement = fscAbstractElement;
export declare type Attributes = fscAttributes;
export declare type DOM = fscDOM;
export declare type FaSymbol = fscFaSymbol;
export declare type FlipProp = fscFlipProp;
export declare type FontawesomeObject = fscFontawesomeObject;
export declare type Icon = fscIcon;
export declare type IconDefinition = fscIconDefinition;
export declare type IconLookup = fscIconLookup;
export declare type IconName = fscIconName;
export declare type IconPack = fscIconPack;
export declare type IconParams = fscIconParams;
export declare type IconPathData = fscIconPathData;
export declare type IconPrefix = fscIconPrefix;
export declare type IconProp = fscIconProp;
export declare type Layer = fscLayer;
export declare type LayerParams = fscLayerParams;
export declare type Library = fscLibrary;
export declare type Params = fscParams;
export declare type PullProp = fscPullProp;
export declare type RotateProp = fscRotateProp;
export declare type SizeProp = fscSizeProp;
export declare type Styles = fscStyles;
export declare type Text = fscText;
export declare type TextParams = fscTextParams;
export declare type Transform = fscTransform;
export declare let config: fsc.Config;
export declare let counter: typeof fsc.counter;
export declare let dom: fscDOM;
export declare let findIconDefinition: typeof fsc.findIconDefinition;
export declare let icon: typeof fsc.icon;
export declare let layer: typeof fsc.layer;
export declare let library: fscLibrary;
export declare let noAuto: typeof fsc.noAuto;
export declare let parse: {
    transform(transformString: string): fscTransform;
    icon(parseIconString: string): fscIconLookup;
};
export declare let text: typeof fsc.text;
export declare let toHtml: typeof fsc.toHtml;
