import * as fsc from '@fortawesome/fontawesome-svg-core';
export let config = fsc.config;
export let counter = fsc.counter;
export let dom = fsc.dom;
export let findIconDefinition = fsc.findIconDefinition;
export let icon = fsc.icon;
export let layer = fsc.layer;
export let library = fsc.library;
export let noAuto = fsc.noAuto;
export let parse = fsc.parse;
export let text = fsc.text;
export let toHtml = fsc.toHtml;
