export declare const searchUsers = "https://discoveryprovider3.audius.co/v1/users/search?query=Brownies&app_name=EXAMPLEAPP";
export declare const getUser = "https://discoveryprovider3.audius.co/v1/users/nlGNe?app_name=EXAMPLEAPP";
export declare const getUserFavorites = "https://discoveryprovider3.audius.co/v1/users/nlGNe?app_name=EXAMPLEAPP";
export declare const getUsersReposts = "https://discoveryprovider3.audius.co/v1/users/string/reposts?app_name=EXAMPLEAPP";
export declare const getUsersMostUsedTrackTags = "https://discoveryprovider3.audius.co/v1/users/string/tags?user_id=string&app_name=EXAMPLEAPP";
export declare const getUsersTracks = "https://discoveryprovider3.audius.co/v1/users/nlGNe/tracks?app_name=EXAMPLEAPP";
export declare const searchPlaylist = "https://discoveryprovider3.audius.co/v1/playlists/search?query=Hot%20New&app_name=EXAMPLEAPP";
export declare const getPlaylist = "https://discoveryprovider3.audius.co/v1/playlists/DOPRl?app_name=EXAMPLEAPP";
export declare const getPlaylistTracks = "https://discoveryprovider3.audius.co/v1/playlists/DOPRl/tracks?app_name=EXAMPLEAPP";
export declare const searchTracks = "https://discoveryprovider3.audius.co/v1/tracks/search?query=baauer%20b2b&app_name=EXAMPLEAPP";
export declare const trendingTracks = "https://discoveryprovider3.audius.co/v1/tracks/trending?app_name=EXAMPLEAPP";
export declare const getTrack = "https://discoveryprovider3.audius.co/v1/tracks/D7KyD?app_name=EXAMPLEAPP";
export declare const streamTrack = "https://discoveryprovider3.audius.co/v1/tracks/D7KyD/stream?app_name=EXAMPLEAPP";
export declare const searchHashtag = "https://discoveryprovider3.audius.co/search/tags?kind=all&limit=15&offset=0&query=taghere&user_tag_count=1";
declare const _default: {
    searchUsers: string;
    getUser: string;
    getUserFavorites: string;
    getUsersReposts: string;
    getUsersMostUsedTrackTags: string;
    getUsersTracks: string;
    searchPlaylist: string;
    getPlaylist: string;
    getPlaylistTracks: string;
    searchTracks: string;
    trendingTracks: string;
    getTrack: string;
    streamTrack: string;
    searchHashtag: string;
};
export default _default;
