/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { GovernorTimelockCompound__factory } from "./GovernorTimelockCompound__factory";
export { ICompoundTimelock__factory } from "./ICompoundTimelock__factory";
