/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as governorTimelockCompoundSol from "./GovernorTimelockCompound.sol";
export type { governorTimelockCompoundSol };
export type { GovernorCountingSimple } from "./GovernorCountingSimple";
export type { GovernorProposalThreshold } from "./GovernorProposalThreshold";
export type { GovernorSettings } from "./GovernorSettings";
export type { GovernorTimelockControl } from "./GovernorTimelockControl";
export type { GovernorVotes } from "./GovernorVotes";
export type { GovernorVotesComp } from "./GovernorVotesComp";
export type { GovernorVotesQuorumFraction } from "./GovernorVotesQuorumFraction";
export type { IGovernorTimelock } from "./IGovernorTimelock";
