/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { GovernorTimelockCompound } from "./GovernorTimelockCompound";
export type { ICompoundTimelock } from "./ICompoundTimelock";
