/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as erc1155StakingSol from "./ERC1155Staking.sol";
export * as synthetixStakingSol from "./SynthetixStaking.sol";
export { ERC1155VestingWallet__factory } from "./ERC1155VestingWallet__factory";
export { ERC721Staking__factory } from "./ERC721Staking__factory";
export { IERC1155Staking__factory } from "./IERC1155Staking__factory";
export { IERC1155VestingWallet__factory } from "./IERC1155VestingWallet__factory";
export { IERC721Staking__factory } from "./IERC721Staking__factory";
export { IZionVestingWallet__factory } from "./IZionVestingWallet__factory";
export { ZionVestingWallet__factory } from "./ZionVestingWallet__factory";
