import * as MixinDecorators from "../../types/Mixin/MixinDecorators.js";
export declare const isApplicationOf: (proto: any, mixin: any) => any;
export declare const hasMixin: (o: any, mixin: any) => boolean;
declare type wrapType = (mixin: any, wrapper: any) => any;
export declare const wrap: wrapType;
declare type unwraptype = (wrapper: any) => any;
export declare const unwrap: unwraptype;
export declare const BaseMixin: MixinDecorators.MixinDecorator;
export declare const Cached: MixinDecorators.MixinDecoratoBroad;
export declare const DeDupe: MixinDecorators.MixinDecoratoBroad;
export {};
