import ethers, { BaseContract as ethBaseContract, BigNumber as ethBigNumber, BigNumberish as ethBigNumberish, Bytes as ethBytes, BytesLike as ethBytesLike, CallOverrides as ethCallOverrides, Contract as ethContract, ContractFactory as ethContractFactory, ContractFunction as ethContractFunction, ContractInterface as ethContractInterface, ContractReceipt as ethContractReceipt, ContractTransaction as ethContractTransaction, Event as ethEvent, EventFilter as ethEventFilter, FixedNumber as ethFixedNumber, Overrides as ethOverrides, PayableOverrides as ethPayableOverrides, PopulatedTransaction as ethPopulatedTransaction, Signature as ethSignature, Signer as ethSigner, Transaction as ethTransaction, UnsignedTransaction as ethUnsignedTransaction, VoidSigner as ethVoidSigner, Wallet as ethWallet, Wordlist as ethWordlist } from 'ethers';
export declare type BaseContract = ethBaseContract;
export declare type BigNumber = ethBigNumber;
export declare type BigNumberish = ethBigNumberish;
export declare type Bytes = ethBytes;
export declare type BytesLike = ethBytesLike;
export declare type CallOverrides = ethCallOverrides;
export declare type Contract = ethContract;
export declare type ContractFactory = ethContractFactory;
export declare type ContractFunction = ethContractFunction;
export declare type ContractInterface = ethContractInterface;
export declare type ContractReceipt = ethContractReceipt;
export declare type ContractTransaction = ethContractTransaction;
export declare type Event = ethEvent;
export declare type EventFilter = ethEventFilter;
export declare type FixedNumber = ethFixedNumber;
export declare type Overrides = ethOverrides;
export declare type PayableOverrides = ethPayableOverrides;
export declare type PopulatedTransaction = ethPopulatedTransaction;
export declare type Signature = ethSignature;
export declare type Signer = ethSigner;
export declare type Transaction = ethTransaction;
export declare type UnsignedTransaction = ethUnsignedTransaction;
export declare type VoidSigner = ethVoidSigner;
export declare type Wallet = ethWallet;
export declare type Wordlist = ethWordlist;
export declare let constants: typeof ethers.ethers.constants;
export declare let errors: typeof ethers.ethers.errors;
export declare let getDefaultProvider: typeof ethers.ethers.getDefaultProvider;
export declare let logger: ethers.ethers.utils.Logger;
export declare let providers: typeof ethers.ethers.providers;
export declare let utils: typeof ethers.ethers.utils;
export declare let version: string;
export declare let wordlists: {
    [locale: string]: ethers.ethers.Wordlist;
};
